In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import neighbors, datasets
import pandas as pd

In [2]:
data = pd.read_csv('../dataset/iris_2D.csv')

In [3]:
print(data)

   Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0


In [4]:
x_data = data[['Petal_Length','Petal_Width']].to_numpy()
x_data = x_data.reshape(6,2)
print(x_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


In [5]:
x_test = np.array([2.6,0.8])
print(x_test)

[2.6 0.8]


In [6]:
x_test = x_test.reshape(1,2)
print(x_test.shape)
print(x_test)

(1, 2)
[[2.6 0.8]]


In [7]:
#distance = np.sqrt((x_data-x_test)**2)
distance = np.sqrt(np.sum((x_data - x_test)**2, axis = 1))
print(distance)

[1.34164079 1.36014705 1.3        1.41421356 2.18403297 1.11803399]


In [8]:
print(0.25**2)

0.0625
